// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI4KxkCy_BM2YOtaoApR2VHdJ1J7CGidA',
    appId: '1:784100962028:web:eaca0671d7f80fbda93fc9',
    messagingSenderId: '784100962028',
    projectId: 'order-app-6e31e',
    authDomain: 'order-app-6e31e.firebaseapp.com',
    storageBucket: 'order-app-6e31e.appspot.com',
    measurementId: 'G-EF3TY34LTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBicwW_DlWFzNsNmLfPV4m5G7i--fYRKYk',
    appId: '1:784100962028:android:cfe4cf4d982cfe72a93fc9',
    messagingSenderId: '784100962028',
    projectId: 'order-app-6e31e',
    storageBucket: 'order-app-6e31e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx6WpkBT8c_imm9kw7IIX0q8eYOE2H6is',
    appId: '1:784100962028:ios:50493e3d5470dfb1a93fc9',
    messagingSenderId: '784100962028',
    projectId: 'order-app-6e31e',
    storageBucket: 'order-app-6e31e.appspot.com',
    iosBundleId: 'com.example.orderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx6WpkBT8c_imm9kw7IIX0q8eYOE2H6is',
    appId: '1:784100962028:ios:50493e3d5470dfb1a93fc9',
    messagingSenderId: '784100962028',
    projectId: 'order-app-6e31e',
    storageBucket: 'order-app-6e31e.appspot.com',
    iosBundleId: 'com.example.orderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI4KxkCy_BM2YOtaoApR2VHdJ1J7CGidA',
    appId: '1:784100962028:web:75fa85b30b94bc91a93fc9',
    messagingSenderId: '784100962028',
    projectId: 'order-app-6e31e',
    authDomain: 'order-app-6e31e.firebaseapp.com',
    storageBucket: 'order-app-6e31e.appspot.com',
    measurementId: 'G-YPG6M3S9V5',
  );
}
